lib/tractabus_web/router.ex
defmodule TractabusWeb.Router do
  use TractabusWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", TractabusWeb do
    pipe_through [:browser, TractabusWeb.Plugs.Guest]

    get "/login", SessionController, :new
    post "/login", SessionController, :create
  end

  scope "/", TractabusWeb do
    pipe_through :browser

    get "/", PageController, :index

    pipe_through TractabusWeb.Plugs.Auth

    delete "/logout", SessionController, :delete

    resources "/profile", UserController
    resources "/user", UserController, only: [:index, :show]
    resources "/articles", ArticleController, only: [:index, :show]
  end

  # Other scopes may use custom stacks.
  # scope "/api", TractabusWeb do
  #   pipe_through :api
  # end
end

lib/tractabus_web/views/layout_view.ex
defmodule TractabusWeb.LayoutView do
  use TractabusWeb, :view
end

lib/tractabus_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>Tractabus</title>
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <!-- Bootstrap table CDN -->
    <link rel="stylesheet" href="https://unpkg.com/bootstrap-table@1.15.2/dist/bootstrap-table.min.css">

  </head>
  <body>
    <header>
      <section class="container">
        <nav role="navigation">
        <%= if(@conn.assigns[:current_user]) do %>
          <ul class="nav nav-pills">
            <li>
              <%= link @conn.assigns.current_user.name, to: Routes.user_path(@conn, :show, @conn.assigns.current_user) %>
            </li>
            <li>
              <%= link "logout", to: Routes.session_path(@conn, :delete), method: :delete %>
            </li>
          </ul>
        <% else %>
          <ul class="nav nav-pills">
            <li>
              <%= link "Register", to: Routes.user_path(@conn, :new) %>
            </li>
            <li>
              <%= link "Sign in", to: Routes.session_path(@conn, :new) %>
            </li>
          </ul>
        <% end %>
        </nav>
        <a href="/">
          <img src="<%= Routes.static_path(@conn, "/images/tractabus_large.png") %>" height="120px" alt="Tractabus Logo"/>
        </a>
      </section>
    </header>
    <main role="main" class="container">
      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
      <%= render @view_module, @view_template, assigns %>
    </main>
    <script type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
    <script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>
    <script src="https://unpkg.com/bootstrap-table@1.15.2/dist/bootstrap-table.min.js"></script>
  </body>
</html>